# -*- coding: utf-8 -*-
"""CRA 评估控制库内容（附录 I 第一/二部分，融合 SAMM 五大功能）。

结构：DOMAINS = [{code,name,samm_function, items:[...]}]
每个 item：code/title/question/cra_ref/guidance(0-5分级说明)/weight/remediation
remediation：[{level_threshold, gap_desc, advice, recommended_tools:[...]}]
"""

DOMAINS = [
    # ───────────── 域1：治理与合规管理（SAMM 治理）─────────────
    {"code": "GOV", "name": "治理与合规管理", "samm_function": "治理 Governance", "order": 1, "items": [
        {"code": "GOV-01", "title": "网络安全策略与责任",
         "question": "组织是否制定了书面的产品网络安全策略，并明确各产品的安全负责人？",
         "cra_ref": "CRA 第13条 制造商义务",
         "guidance": "0=无策略；2=有零散文档；3=有书面策略并指定负责人；5=策略覆盖全产品线、定期评审、与CRA要求映射",
         "weight": 1.0,
         "remediation": [{"level_threshold": 2, "gap_desc": "缺少体系化的产品网络安全策略与责任分配",
                          "advice": "制定书面网络安全策略，指定每个产品的安全负责人(PSIRT)，建立与CRA义务的映射台账",
                          "recommended_tools": ["SDLC-SER 研发安全生命周期服务"]}]},
        {"code": "GOV-02", "title": "CRA 适用性与产品分类",
         "question": "是否已判定产品属于 CRA 的默认类/重要产品(Class I/II)/关键产品，并确定符合性评估路径？",
         "cra_ref": "CRA 附录 III/IV 产品分类",
         "guidance": "0=未判定；3=已分类并记录依据；5=已分类且明确合格评定模块(A/B+C/H)与是否需公告机构",
         "weight": 1.5,
         "remediation": [{"level_threshold": 2, "gap_desc": "未完成 CRA 产品分类，无法确定合规路径",
                          "advice": "依据附录III/IV判定产品类别，明确是否需第三方公告机构与对应合格评定模块",
                          "recommended_tools": ["SDLC-SER 研发安全生命周期服务"]}]},
        {"code": "GOV-03", "title": "风险评估机制",
         "question": "是否对产品进行基于风险的网络安全风险评估，并形成风险登记册？",
         "cra_ref": "CRA 附录 I 第一部分(1) 基于风险",
         "guidance": "0=无；2=一次性评估；3=有风险登记册；5=持续更新、含固有/剩余风险评分与处置计划",
         "weight": 1.5,
         "remediation": [{"level_threshold": 2, "gap_desc": "缺少结构化产品网络安全风险评估",
                          "advice": "建立风险登记册，评定固有/剩余风险，制定处置计划并与控制项关联",
                          "recommended_tools": ["SDLC-SER 研发安全生命周期服务", "PENTEST 渗透测试服务"]}]},
        {"code": "GOV-04", "title": "供应链与第三方组件管理",
         "question": "是否管理第三方/开源组件清单、来源与许可证，并评估其安全风险？",
         "cra_ref": "CRA 附录 I 第二部分(1) 组件",
         "guidance": "0=无清单；3=有组件清单与许可证；5=组件级漏洞跟踪+供应商风险分级+SBOM 联动",
         "weight": 1.0,
         "remediation": [{"level_threshold": 2, "gap_desc": "第三方/开源组件缺乏管理与风险评估",
                          "advice": "建立组件资产台账，引入 SCA 持续识别组件漏洞与许可证合规",
                          "recommended_tools": ["SCA 源代码软件成分分析", "OSS-AUDIT 开源许可测试服务"]}]},
    ]},

    # ───────────── 域2：安全设计（SAMM 设计）─────────────
    {"code": "DES", "name": "安全设计", "samm_function": "设计 Design", "order": 2, "items": [
        {"code": "DES-01", "title": "默认安全配置",
         "question": "产品是否以安全的默认配置交付（默认关闭非必要功能、强制改默认口令）？",
         "cra_ref": "CRA 附录 I 第一部分(2)(a)",
         "guidance": "0=默认不安全；3=部分安全默认；5=最小权限默认、强制首次改密、非必要服务默认关闭",
         "weight": 1.5,
         "remediation": [{"level_threshold": 2, "gap_desc": "产品默认配置不满足安全交付要求",
                          "advice": "实施安全默认基线：禁用默认口令、关闭非必要端口/服务、最小化默认权限",
                          "recommended_tools": ["BAT 二进制安全检测", "PENTEST 渗透测试服务"]}]},
        {"code": "DES-02", "title": "攻击面最小化",
         "question": "是否通过设计减少产品的攻击面（最小化暴露接口、服务与权限）？",
         "cra_ref": "CRA 附录 I 第一部分(2)(j)",
         "guidance": "0=未考虑；3=识别并记录攻击面；5=系统化攻击面分析+持续裁剪",
         "weight": 1.0,
         "remediation": [{"level_threshold": 2, "gap_desc": "攻击面未经系统分析与裁剪",
                          "advice": "开展攻击面建模，移除非必要接口与权限，对暴露面做持续监控",
                          "recommended_tools": ["BAT 二进制安全检测", "FUZZ 黑盒协议模糊测试"]}]},
        {"code": "DES-03", "title": "纵深防御",
         "question": "产品安全设计是否采用纵深防御（多层防护、失效安全）？",
         "cra_ref": "CRA 附录 I 第一部分(2)(k)",
         "guidance": "0=单层；3=多层防护；5=纵深防御+失效安全(fail-secure)+边界隔离",
         "weight": 1.0,
         "remediation": [{"level_threshold": 2, "gap_desc": "缺乏纵深防御设计",
                          "advice": "引入多层防护与失效安全机制，关键功能边界隔离",
                          "recommended_tools": ["PENTEST 渗透测试服务"]}]},
        {"code": "DES-04", "title": "威胁建模",
         "question": "是否在设计阶段开展威胁建模并将缓解措施纳入需求？",
         "cra_ref": "CRA 附录 I 第一部分(1) 安全设计",
         "guidance": "0=无；3=关键模块威胁建模；5=全产品威胁建模+缓解项可追溯到需求/测试",
         "weight": 1.0,
         "remediation": [{"level_threshold": 2, "gap_desc": "设计阶段缺少威胁建模",
                          "advice": "对关键数据流开展 STRIDE 威胁建模，缓解项纳入安全需求并验证",
                          "recommended_tools": ["SDLC-SER 研发安全生命周期服务"]}]},
    ]},

    # ───────────── 域3：安全实现（SAMM 实施）─────────────
    {"code": "IMP", "name": "安全实现", "samm_function": "实施 Implementation", "order": 3, "items": [
        {"code": "IMP-01", "title": "访问控制与身份认证",
         "question": "产品是否实施了适当的访问控制与身份认证机制保护未授权访问？",
         "cra_ref": "CRA 附录 I 第一部分(2)(b)",
         "guidance": "0=无；3=基础认证+授权；5=强认证(MFA可选)+细粒度授权+会话保护",
         "weight": 1.5,
         "remediation": [{"level_threshold": 2, "gap_desc": "访问控制/认证机制不足以防护未授权访问",
                          "advice": "实施细粒度授权与强身份认证，保护凭据与会话",
                          "recommended_tools": ["SAST 静态代码质量与安全检测", "PENTEST 渗透测试服务"]}]},
        {"code": "IMP-02", "title": "数据机密性（加密）",
         "question": "产品是否对存储与传输中的敏感数据进行加密保护？",
         "cra_ref": "CRA 附录 I 第一部分(2)(c)",
         "guidance": "0=明文；3=传输加密；5=传输+存储加密+密钥管理规范",
         "weight": 1.5,
         "remediation": [{"level_threshold": 2, "gap_desc": "敏感数据缺乏端到端加密保护",
                          "advice": "对传输与存储数据启用强加密，规范密钥全生命周期管理",
                          "recommended_tools": ["SAST 静态代码质量与安全检测", "BAT 二进制安全检测"]}]},
        {"code": "IMP-03", "title": "数据完整性",
         "question": "产品是否保护数据、命令、配置与固件的完整性（防篡改）？",
         "cra_ref": "CRA 附录 I 第一部分(2)(d)",
         "guidance": "0=无；3=校验机制；5=签名校验+防回滚+完整性度量",
         "weight": 1.0,
         "remediation": [{"level_threshold": 2, "gap_desc": "缺乏完整性保护，易被篡改",
                          "advice": "引入签名校验与防回滚，对固件/配置做完整性度量",
                          "recommended_tools": ["BAT 二进制安全检测"]}]},
        {"code": "IMP-04", "title": "数据最小化",
         "question": "产品是否仅处理实现其功能所必需的数据（数据最小化）？",
         "cra_ref": "CRA 附录 I 第一部分(2)(e)",
         "guidance": "0=过度收集；3=部分最小化；5=严格最小化+数据用途记录",
         "weight": 0.8,
         "remediation": [{"level_threshold": 2, "gap_desc": "存在与功能无关的数据收集",
                          "advice": "梳理数据流，移除非必要数据收集，记录数据处理用途",
                          "recommended_tools": ["SAST 静态代码质量与安全检测"]}]},
        {"code": "IMP-05", "title": "安全编码与代码质量",
         "question": "是否执行安全编码规范并通过静态分析检测代码缺陷？",
         "cra_ref": "CRA 附录 I 第一部分(1) 无已知可利用漏洞",
         "guidance": "0=无；2=人工评审；3=SAST 接入CI；5=SAST+规范门禁+误报治理+趋势管理",
         "weight": 1.2,
         "remediation": [{"level_threshold": 2, "gap_desc": "缺乏自动化安全编码检测",
                          "advice": "将 SAST 接入CI流水线设质量门禁，落地MISRA/CERT/GJB编码规范",
                          "recommended_tools": ["SAST 静态代码质量与安全检测", "CodingHawk 代码审计智能体", "SAST-SER 编码规范咨询服务"]}]},
        {"code": "IMP-06", "title": "可用性与抗拒绝服务",
         "question": "产品是否具备抵御拒绝服务、保障关键功能可用性的设计？",
         "cra_ref": "CRA 附录 I 第一部分(2)(g)(h)",
         "guidance": "0=无；3=基础限流；5=资源隔离+限流+降级保护关键功能",
         "weight": 0.8,
         "remediation": [{"level_threshold": 2, "gap_desc": "缺乏抗DoS与可用性保障",
                          "advice": "引入限流、资源隔离与降级机制，对协议解析做健壮性测试",
                          "recommended_tools": ["FUZZ 黑盒协议模糊测试"]}]},
    ]},

    # ───────────── 域4：安全验证（SAMM 验证）─────────────
    {"code": "VER", "name": "安全验证", "samm_function": "验证 Verification", "order": 4, "items": [
        {"code": "VER-01", "title": "漏洞检测与测试",
         "question": "产品发布前是否经过系统化的安全测试（SAST/SCA/动态/模糊测试）？",
         "cra_ref": "CRA 附录 I 第二部分(3) 测试",
         "guidance": "0=无；2=单一手段；3=多手段组合；5=SAST+SCA+Fuzz+渗透全覆盖且结果闭环",
         "weight": 1.5,
         "remediation": [{"level_threshold": 2, "gap_desc": "安全测试手段单一或缺失",
                          "advice": "组合 SAST/SCA/模糊测试/渗透测试形成多层验证，结果纳入修复闭环",
                          "recommended_tools": ["SAST 静态代码质量与安全检测", "SCA 源代码软件成分分析", "FUZZ 黑盒协议模糊测试", "PENTEST 渗透测试服务"]}]},
        {"code": "VER-02", "title": "SBOM 生成与维护",
         "question": "是否为产品生成并维护机器可读的软件物料清单(SBOM)？",
         "cra_ref": "CRA 附录 I 第二部分(1) SBOM",
         "guidance": "0=无；3=生成一次性SBOM；5=每版本自动生成CycloneDX/SPDX并随漏洞库联动",
         "weight": 1.2,
         "remediation": [{"level_threshold": 2, "gap_desc": "缺少机器可读 SBOM",
                          "advice": "每个版本自动生成 CycloneDX/SPDX SBOM，与漏洞库持续比对",
                          "recommended_tools": ["SCA 源代码软件成分分析", "SBOM-SER 软件成分分析测试服务"]}]},
        {"code": "VER-03", "title": "二进制/固件安全验证",
         "question": "对交付的二进制或固件是否进行成分分析与安全检测？",
         "cra_ref": "CRA 附录 I 第二部分(3)",
         "guidance": "0=无；3=人工检查；5=自动二进制成分分析+敏感数据/加密算法识别",
         "weight": 1.0,
         "remediation": [{"level_threshold": 2, "gap_desc": "二进制/固件未经安全检测",
                          "advice": "对固件做二进制成分分析，识别硬编码密钥、弱加密与敏感数据",
                          "recommended_tools": ["BAT 二进制安全检测", "BAT-SER 固件安全测试"]}]},
        {"code": "VER-04", "title": "大模型/AI 组件安全",
         "question": "若产品含大模型/AI 组件，是否对其进行安全检测（如适用）？",
         "cra_ref": "CRA 附录 I 第一部分 安全属性（AI适用）",
         "guidance": "N/A 或 0=未检测；3=基础检测；5=基座溯源+漏洞+知识产权+智能体安全全覆盖",
         "weight": 0.6,
         "remediation": [{"level_threshold": 2, "gap_desc": "AI/大模型组件缺乏专项安全检测",
                          "advice": "对大模型全生命周期做安全检测：基座溯源、漏洞、智能体安全",
                          "recommended_tools": ["MST 大模型安全检测", "MST-SER 大模型安全检测服务"]}]},
    ]},

    # ───────────── 域5：漏洞处理与运维（SAMM 运维 + 附录I第二部分）─────────────
    {"code": "VLN", "name": "漏洞处理", "samm_function": "运维 Operations", "order": 5, "items": [
        {"code": "VLN-01", "title": "漏洞识别与登记",
         "question": "是否建立漏洞识别、登记与定级(CVSS)的统一流程？",
         "cra_ref": "CRA 附录 I 第二部分(1)(2)",
         "guidance": "0=无；3=有登记与CVSS定级；5=统一漏洞台账+来源集成+SLA定级",
         "weight": 1.2,
         "remediation": [{"level_threshold": 2, "gap_desc": "漏洞缺乏统一识别与定级流程",
                          "advice": "建立漏洞台账，统一CVSS定级与处置SLA，集成检测工具结果",
                          "recommended_tools": ["GuardFox AI漏洞分析验证", "SCA 源代码软件成分分析"]}]},
        {"code": "VLN-02", "title": "及时安全更新",
         "question": "是否能在支持期内及时、免费地向用户提供安全更新？",
         "cra_ref": "CRA 附录 I 第二部分(7)(8) 安全更新",
         "guidance": "0=无；3=可发更新但不及时；5=及时+免费+与功能更新分离+可自动分发",
         "weight": 1.5,
         "remediation": [{"level_threshold": 2, "gap_desc": "安全更新机制不健全或不及时",
                          "advice": "建立独立的安全更新通道，确保支持期内免费及时分发并与功能更新分离",
                          "recommended_tools": ["SDLC-SER 研发安全生命周期服务"]}]},
        {"code": "VLN-03", "title": "协调漏洞披露政策(CVD)",
         "question": "是否制定并公开协调漏洞披露政策与漏洞接收通道？",
         "cra_ref": "CRA 附录 I 第二部分(5) CVD",
         "guidance": "0=无；3=有内部流程；5=公开CVD政策+对外接收通道+披露时间线管理",
         "weight": 1.2,
         "remediation": [{"level_threshold": 2, "gap_desc": "缺少公开的协调漏洞披露政策",
                          "advice": "制定并公开 CVD 政策，建立对外漏洞接收通道与披露时间线管理",
                          "recommended_tools": ["SDLC-SER 研发安全生命周期服务"]}]},
        {"code": "VLN-04", "title": "漏洞修复与回归",
         "question": "漏洞修复是否经验证并做回归测试，确认不引入新风险？",
         "cra_ref": "CRA 附录 I 第二部分(2)",
         "guidance": "0=无验证；3=修复后人工验证；5=修复+自动回归+复测闭环",
         "weight": 1.0,
         "remediation": [{"level_threshold": 2, "gap_desc": "漏洞修复缺乏验证与回归",
                          "advice": "修复后执行复测与自动回归，确认闭环且不引入新缺陷",
                          "recommended_tools": ["SAST 静态代码质量与安全检测", "GuardFox AI漏洞分析验证"]}]},
        {"code": "VLN-05", "title": "安全相关事件日志",
         "question": "产品是否记录安全相关事件并支持监测访问/修改活动？",
         "cra_ref": "CRA 附录 I 第一部分(2)(l) 日志",
         "guidance": "0=无；3=基础日志；5=结构化安全日志+防篡改+可导出审计",
         "weight": 0.8,
         "remediation": [{"level_threshold": 2, "gap_desc": "安全事件日志记录不足",
                          "advice": "记录访问/修改等安全事件，日志防篡改并可导出审计",
                          "recommended_tools": ["BAT 二进制安全检测"]}]},
    ]},

    # ───────────── 域6：合规通报与文档（CRA 第14条 + 附录V/VII）─────────────
    {"code": "RPT", "name": "通报与合规文档", "samm_function": "治理 Governance", "order": 6, "items": [
        {"code": "RPT-01", "title": "漏洞/事件通报能力(24h/72h/14d)",
         "question": "是否具备向 ENISA/CSIRT 按 24h/72h/14d 时限通报已被利用漏洞与严重事件的流程？",
         "cra_ref": "CRA 第14条 通报义务",
         "guidance": "0=无；3=有内部流程；5=时限看板+模板+SRP/CSIRT提交通道+演练",
         "weight": 1.5,
         "remediation": [{"level_threshold": 2, "gap_desc": "缺乏 CRA 第14条法定时限通报能力",
                          "advice": "建立 24h/72h/14d 通报流程与模板，对接 ENISA 单一报告平台(SRP)/CSIRT，定期演练",
                          "recommended_tools": ["SDLC-SER 研发安全生命周期服务"]}]},
        {"code": "RPT-02", "title": "技术文档(附录VII)",
         "question": "是否按附录 VII 维护完整的技术文档并贯穿支持期更新？",
         "cra_ref": "CRA 附录 VII 技术文档",
         "guidance": "0=缺失；3=有主要文档；5=按附录VII清单齐套+持续更新+版本化",
         "weight": 1.2,
         "remediation": [{"level_threshold": 2, "gap_desc": "技术文档不齐或未持续更新",
                          "advice": "按附录VII清单建立技术文档台账，标记持续更新项并版本化留存",
                          "recommended_tools": ["SDLC-SER 研发安全生命周期服务"]}]},
        {"code": "RPT-03", "title": "欧盟符合性声明(DoC)与CE标记",
         "question": "是否能出具符合附录 V 的欧盟符合性声明并正确加贴 CE 标记？",
         "cra_ref": "CRA 附录 V DoC / CE 标记",
         "guidance": "0=无；3=有DoC草稿；5=DoC齐全+签署+10年留存+CE标记合规",
         "weight": 1.0,
         "remediation": [{"level_threshold": 2, "gap_desc": "缺少合规的 DoC 与 CE 标记安排",
                          "advice": "依附录V要素编制并签署DoC，保存10年/支持期取长者，正确加贴CE标记",
                          "recommended_tools": ["SDLC-SER 研发安全生命周期服务"]}]},
        {"code": "RPT-04", "title": "用户安全信息(附录II)",
         "question": "是否向用户提供附录 II 要求的安全使用说明与支持期信息？",
         "cra_ref": "CRA 附录 II 用户信息",
         "guidance": "0=无；3=有基础说明；5=完整安全手册+支持期/EoL说明+漏洞报告渠道",
         "weight": 0.8,
         "remediation": [{"level_threshold": 2, "gap_desc": "用户安全信息不完整",
                          "advice": "编制用户安全手册，载明安全配置、支持期/EoL与漏洞报告渠道",
                          "recommended_tools": ["SDLC-SER 研发安全生命周期服务"]}]},
    ]},
]
